//! The macOS backend, built on polling `NSPasteboard.changeCount`.
//!
//! macOS is the only one of the three platforms with no clipboard change notification at all, and
//! there never has been one. Every clipboard utility on the platform polls the change counter, and
//! so does this. That is cheap: `changeCount` is an integer read, not a content read.
//!
//! Four macOS specific decisions shape everything below, and each one traces to a documented
//! failure or to Apple's own behaviour:
//!
//! 1. **Poll at 500 ms.** Maccy, `Clipy` and `CopyQ` all ship 500 ms and KDE Connect uses
//!    1000 ms.
//!    Apple's guidance is to investigate any idle application that wakes more than once a second,
//!    so the 200 ms an earlier draft of the plan suggested was five times too eager for a process
//!    that is meant to sit in the menu bar all day.
//! 2. **Pasteboard access happens on one thread, the one that owns the watcher.** `AppKit` is not
//!    thread safe, and `ClipCascade` issue 173 is repeated `EXC_BAD_ACCESS` inside
//!    `NSPasteboard`
//!    from polling it off the main thread. See [`MacosClipboard`] for how that is enforced here
//!    rather than merely intended.
//! 3. **App Nap will throttle the timer** and stop sync silently when the app is not focused, so
//!    the watcher holds a background activity token for its whole life.
//! 4. **The pasteboard privacy alert.** Since macOS 15.4 the system can alert the user when an
//!    application programmatically reads the general pasteboard. Reading the type list is not a
//!    content read, so the sensitivity check below happens first and the content read happens only
//!    when the counter actually moved, which holds gateable calls to at most one per real copy.
//!    See [`Permission`].
//!
//! Receiving never needs permission: writing to the pasteboard is not gated. A Mac that is denied
//! read access still receives clips from the other machines. Only sending from the Mac stops.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;

use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSActivityOptions, NSProcessInfo, NSString};

use crate::error::{Error, Result};
use crate::{ClipContent, ClipEvent, ClipboardWatcher, WriteReceipt};

/// How often the change counter is read.
///
/// This is an integer read, not a content read, so the cost is a wakeup rather than any pasteboard
/// work. 500 ms is what the established macOS clipboard utilities ship.
pub const POLL_INTERVAL: Duration = Duration::from_millis(500);

/// Slack given to the system for coalescing our wakeups with other work.
///
/// A timer that insists on firing at an exact instant prevents the CPU from staying idle. Allowing
/// 100 ms of drift lets the scheduler batch this poll with whatever else is waking up.
pub const POLL_TOLERANCE: Duration = Duration::from_millis(100);

/// The uniform type identifier for plain UTF-8 text.
///
/// This is the documented value of `NSPasteboardTypeString`. That symbol is an `extern "C"`
/// static, and `objc2-app-kit` exposes no safe accessor for it, so reading it would require an
/// `unsafe` block. Building the string here instead keeps `forbid(unsafe_code)` intact across the
/// crate, at the cost of one small allocation per read, which is the better trade.
pub const UTI_UTF8_TEXT: &str = "public.utf8-plain-text";

/// Marks content the source application considers confidential.
///
/// These are the nspasteboard.org conventions rather than Apple types, which is why they are
/// plain strings here: they exist by agreement between applications, not in the SDK. `KeePassXC`
/// writes the concealed type, and the established macOS clipboard managers read it.
pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// Marks content that is on the pasteboard only momentarily.
pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
/// Marks content an application generated, which the person never chose to copy.
pub const AUTOGENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// What the system will do about programmatic pasteboard reads.
///
/// The four states come straight from `NSPasteboardAccessBehavior`. Their raw values are pinned by
/// the `objc2-app-kit` bindings rather than guessed here, and [`Permission::from_raw`] treats
/// anything unrecognised as a refusal, so a future fifth case fails closed into receive only mode
/// rather than into a prompt on every copy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Permission {
    /// No alert has ever fired, and the app is not listed in System Settings yet.
    ///
    /// Reads still work in this state, which is why this is the state a Mac is in today: the
    /// feature is a per app developer preview and is not on by default in shipping macOS 26.
    Default,
    /// The system prompts on every read. Unusable for a background watcher.
    Ask,
    /// A permanent grant. The steady state to aim for.
    AlwaysAllow,
    /// Permanently denied. Receiving still works; sending does not.
    AlwaysDeny,
    /// Something the bindings did not describe, treated as a refusal.
    Unknown(isize),
}

impl Permission {
    /// Maps the raw `NSInteger` to a state.
    #[must_use]
    pub fn from_raw(raw: isize) -> Self {
        match raw {
            0 => Self::Default,
            1 => Self::Ask,
            2 => Self::AlwaysAllow,
            3 => Self::AlwaysDeny,
            other => Self::Unknown(other),
        }
    }

    /// Whether a background content read is safe to perform right now.
    ///
    /// `Default` qualifies because no alert has fired yet and reads work. The first content read
    /// in that state is the one budgeted prompt, after which the state flips to `Ask` and the
    /// watcher must stop and hand over to onboarding.
    #[must_use]
    pub const fn may_read_in_background(self) -> bool {
        matches!(self, Self::Default | Self::AlwaysAllow)
    }

    /// Whether the app layer should show the onboarding flow.
    #[must_use]
    pub const fn needs_onboarding(self) -> bool {
        matches!(self, Self::Ask)
    }

    /// A short label for the tray and diagnostics. Never content.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Default => "not yet prompted",
            Self::Ask => "asking on every read",
            Self::AlwaysAllow => "allowed",
            Self::AlwaysDeny => "denied",
            Self::Unknown(_) => "unrecognised, treated as denied",
        }
    }
}

/// The deep link to the System Settings pane that grants the permission.
///
/// Verified by two independent developers and shipped through App Review. The modern pane
/// identifier is a plausible future rename, so [`SETTINGS_URL_FALLBACK`] exists for when the
/// first one stops opening.
pub const SETTINGS_URL: &str =
    "x-apple.systempreferences:com.apple.preference.security?Privacy_Pasteboard";
/// The modern pane identifier, tried if [`SETTINGS_URL`] fails to open.
pub const SETTINGS_URL_FALLBACK: &str =
    "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension?Privacy_Pasteboard";

/// Whether a set of pasteboard types means the content must not be read.
///
/// Taken as plain data so the decision is a pure function, testable on any platform rather than
/// only on a Mac. All three markers are honoured, not just the concealed one: transient content is
/// on the pasteboard momentarily by design, and auto generated content was never copied by a
/// person, so neither belongs on another machine.
#[must_use]
pub fn is_sensitive(types: &[String]) -> bool {
    types
        .iter()
        .any(|t| t == CONCEALED_TYPE || t == TRANSIENT_TYPE || t == AUTOGENERATED_TYPE)
}

/// Whether a change counter value describes our own write.
///
/// `clearContents` returns the counter value its own change produced, so the value captured when
/// writing identifies that write exactly. This is layer three of loop prevention, and macOS gives
/// the cleanest version of it: no hashing, no time window, no guessing.
#[must_use]
pub fn is_our_own_write(current: isize, last_written: Option<isize>) -> bool {
    match last_written {
        Some(written) => current == written,
        None => false,
    }
}

/// Whether the counter moved since the last observation.
#[must_use]
pub fn changed(current: isize, last_seen: Option<isize>) -> bool {
    match last_seen {
        Some(seen) => current != seen,
        // The first observation establishes a baseline. It is never an event, because the
        // pasteboard already held something before the watcher started and rebroadcasting that on
        // every launch would clobber whatever another machine copied more recently.
        None => false,
    }
}

/// The macOS pasteboard.
///
/// # Threading
///
/// `AppKit` is not thread safe and `NSPasteboard` must not be touched from several threads.
/// Nothing in this type is `Sync`, and the `Retained<NSPasteboard>` handle is not held in the
/// struct at all: it is fetched inside [`ClipboardWatcher::run`] and lives only on the thread that
/// runs the loop. So the pasteboard is reachable from exactly one thread by construction, and the
/// only cross thread channel is the shutdown flag, which is an atomic. That is the structural
/// enforcement: a second thread has nothing to call a pasteboard method on.
///
/// Note that `objc2-app-kit` does not demand a `MainThreadMarker` for `NSPasteboard`, so the
/// compiler will not enforce main thread affinity on your behalf. Run the watcher on the thread
/// the application treats as its main thread.
pub struct MacosClipboard {
    shutdown: Arc<AtomicBool>,
    /// Counter value produced by our own last write.
    last_written: Option<isize>,
    /// Counter value at the last poll.
    last_seen: Option<isize>,
}

impl MacosClipboard {
    /// Prepares the watcher.
    ///
    /// # Errors
    ///
    /// Currently infallible, and returns `Result` so that adding a real failure later is not a
    /// breaking change for callers.
    pub fn connect() -> Result<Self> {
        Ok(Self {
            shutdown: Arc::new(AtomicBool::new(false)),
            last_written: None,
            last_seen: None,
        })
    }

    /// A handle that can ask the watch loop to stop from another thread.
    #[must_use]
    pub fn shutdown_handle(&self) -> Arc<AtomicBool> {
        Arc::clone(&self.shutdown)
    }

    /// What the system will currently do about a programmatic read.
    ///
    /// The app layer drives onboarding from this. It is a state query rather than a content read,
    /// so it is expected to be free of alerts, though that specific point is inferred from the
    /// absence of privacy language on the property rather than documented by Apple.
    #[must_use]
    pub fn permission() -> Permission {
        let pasteboard = NSPasteboard::generalPasteboard();
        Permission::from_raw(pasteboard.accessBehavior().0)
    }

    /// Reads the pasteboard type list.
    ///
    /// This is deliberately separate from reading content, and always happens first, because the
    /// type list is not content and the sensitivity decision must never require touching a value
    /// the source application marked confidential.
    fn types(pasteboard: &NSPasteboard) -> Vec<String> {
        match pasteboard.types() {
            Some(types) => types.to_vec().iter().map(ToString::to_string).collect(),
            None => Vec::new(),
        }
    }

    /// Reads the pasteboard as text, having already decided it is safe to read.
    ///
    /// Returns `Result` to match the other backends, whose reads genuinely fail: the shared call
    /// site matches on the error variants, so narrowing this signature would fork that shape.
    #[allow(clippy::unnecessary_wraps)]
    fn read_text(pasteboard: &NSPasteboard) -> Result<Option<ClipEvent>> {
        let types = Self::types(pasteboard);

        if is_sensitive(&types) {
            return Ok(Some(ClipEvent {
                content: ClipContent::Text(String::new()),
                sensitive: true,
            }));
        }

        let text_type = NSString::from_str(UTI_UTF8_TEXT);
        let Some(raw) = pasteboard.stringForType(&text_type) else {
            // An image or a file promise, which v1 does not sync.
            return Ok(None);
        };

        // Normalize at exactly one boundary, here, so the same text hashes identically on every
        // platform. Skipping this is how two machines grow the text on every hop.
        let text = asli_core::normalize(&raw.to_string()).into_owned();
        if !asli_core::is_syncable(&text) {
            return Ok(None);
        }

        Ok(Some(ClipEvent {
            content: ClipContent::Text(text),
            sensitive: false,
        }))
    }

    /// Puts text on the pasteboard and records the counter value it produced.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Write`] if the pasteboard refuses the write.
    pub fn set_text(&mut self, text: &str) -> Result<WriteReceipt> {
        let pasteboard = NSPasteboard::generalPasteboard();

        // clearContents returns the change count its own change produced, which is what makes
        // recognising our own write exact on this platform.
        let seq = pasteboard.clearContents();

        let native = asli_core::to_platform(text, asli_core::LineEnding::Lf);
        let value = NSString::from_str(&native);

        let text_type = NSString::from_str(UTI_UTF8_TEXT);
        if !pasteboard.setString_forType(&value, &text_type) {
            return Err(Error::Write("the pasteboard refused the write".to_owned()));
        }

        self.last_written = Some(seq);
        self.last_seen = Some(seq);

        Ok(WriteReceipt {
            seq: u64::try_from(seq).ok(),
        })
    }
}

impl ClipboardWatcher for MacosClipboard {
    fn run(&mut self, sink: &mut dyn FnMut(ClipEvent)) -> Result<()> {
        // Fetched here rather than stored, so the pasteboard handle exists only on this thread.
        let pasteboard = NSPasteboard::generalPasteboard();

        // Without this, App Nap throttles the timer once the app loses focus and sync stops with
        // no error anywhere. The token is held for the life of the loop and released by being
        // dropped, which avoids the one unsafe function in this area, endActivity.
        let process = NSProcessInfo::processInfo();
        let _activity = process.beginActivityWithOptions_reason(
            NSActivityOptions::Background,
            &NSString::from_str("watching the pasteboard for clipboard sync"),
        );

        // Establish the baseline without reporting it. Whatever is on the pasteboard now predates
        // the watcher and is not an event.
        self.last_seen = Some(pasteboard.changeCount());

        loop {
            if self.shutdown.load(Ordering::Relaxed) {
                return Ok(());
            }

            std::thread::sleep(POLL_INTERVAL);

            if self.shutdown.load(Ordering::Relaxed) {
                return Ok(());
            }

            let current = pasteboard.changeCount();

            if !changed(current, self.last_seen) {
                continue;
            }
            self.last_seen = Some(current);

            if is_our_own_write(current, self.last_written) {
                continue;
            }

            // Only now, on a real change, is any gateable call made, and the type list is checked
            // before the content so a marked secret is never read at all.
            match Self::read_text(&pasteboard) {
                Ok(Some(event)) => sink(event),
                // No text on the pasteboard, or a read that lost a race with whatever wrote it.
                // Both are routine and neither should stop the watcher.
                Ok(None) | Err(Error::Read(_) | Error::NotUtf8) => {}
                Err(other) => return Err(other),
            }
        }
    }

    fn shutdown(&self) {
        self.shutdown.store(true, Ordering::Relaxed);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_text_is_not_sensitive() {
        let types = vec![UTI_UTF8_TEXT.to_owned(), "NSStringPboardType".to_owned()];
        assert!(!is_sensitive(&types));
    }

    #[test]
    fn a_concealed_marker_means_skip() {
        let types = vec![UTI_UTF8_TEXT.to_owned(), CONCEALED_TYPE.to_owned()];
        assert!(
            is_sensitive(&types),
            "a password manager marking its copy concealed is the case this exists for"
        );
    }

    #[test]
    fn transient_and_autogenerated_are_skipped_too() {
        assert!(is_sensitive(&[TRANSIENT_TYPE.to_owned()]));
        assert!(is_sensitive(&[AUTOGENERATED_TYPE.to_owned()]));
    }

    #[test]
    fn an_empty_type_list_is_not_sensitive() {
        assert!(!is_sensitive(&[]));
    }

    #[test]
    fn permission_values_match_the_bindings() {
        use objc2_app_kit::NSPasteboardAccessBehavior;
        // Pinned against objc2-app-kit rather than guessed, and asserted here so a binding change
        // cannot silently remap the states.
        assert_eq!(Permission::from_raw(0), Permission::Default);
        assert_eq!(Permission::from_raw(1), Permission::Ask);
        assert_eq!(Permission::from_raw(2), Permission::AlwaysAllow);
        assert_eq!(Permission::from_raw(3), Permission::AlwaysDeny);
        assert_eq!(NSPasteboardAccessBehavior::Default.0, 0);
        assert_eq!(NSPasteboardAccessBehavior::Ask.0, 1);
        assert_eq!(NSPasteboardAccessBehavior::AlwaysAllow.0, 2);
        assert_eq!(NSPasteboardAccessBehavior::AlwaysDeny.0, 3);
    }

    #[test]
    fn an_unrecognised_state_fails_closed() {
        let unknown = Permission::from_raw(99);
        assert_eq!(unknown, Permission::Unknown(99));
        assert!(
            !unknown.may_read_in_background(),
            "a state we do not understand must not authorise a background read"
        );
        assert!(!unknown.needs_onboarding());
    }

    #[test]
    fn only_default_and_always_allow_permit_background_reads() {
        assert!(Permission::Default.may_read_in_background());
        assert!(Permission::AlwaysAllow.may_read_in_background());
        assert!(!Permission::Ask.may_read_in_background());
        assert!(!Permission::AlwaysDeny.may_read_in_background());
    }

    #[test]
    fn ask_is_the_state_that_needs_onboarding() {
        // Ask prompts on every read, so a watcher must stop rather than degrade.
        assert!(Permission::Ask.needs_onboarding());
        assert!(!Permission::Default.needs_onboarding());
        assert!(!Permission::AlwaysAllow.needs_onboarding());
        assert!(!Permission::AlwaysDeny.needs_onboarding());
    }

    #[test]
    fn every_state_has_a_label() {
        for state in [
            Permission::Default,
            Permission::Ask,
            Permission::AlwaysAllow,
            Permission::AlwaysDeny,
            Permission::Unknown(7),
        ] {
            assert!(!state.label().is_empty());
        }
    }

    #[test]
    fn our_own_write_is_recognised_exactly() {
        assert!(is_our_own_write(42, Some(42)));
        assert!(!is_our_own_write(43, Some(42)));
    }

    #[test]
    fn without_a_recorded_write_nothing_is_suppressed() {
        // Failing open is correct here: the content hash guard in asli-core is the second layer,
        // and suppressing a real copy is worse than sending one extra.
        assert!(!is_our_own_write(42, None));
    }

    #[test]
    fn the_first_observation_is_a_baseline_not_an_event() {
        assert!(
            !changed(100, None),
            "whatever is on the pasteboard at startup predates the watcher"
        );
    }

    #[test]
    fn a_moved_counter_is_a_change() {
        assert!(changed(101, Some(100)));
        assert!(!changed(100, Some(100)));
    }

    #[test]
    fn the_poll_interval_respects_apples_guidance() {
        // Apple asks that an idle app not wake more than once a second.
        assert_eq!(POLL_INTERVAL, Duration::from_millis(500));
        assert!(POLL_INTERVAL >= Duration::from_millis(500));
        assert!(POLL_TOLERANCE < POLL_INTERVAL);
    }

    #[test]
    fn both_settings_urls_target_the_pasteboard_pane() {
        assert!(SETTINGS_URL.contains("Privacy_Pasteboard"));
        assert!(SETTINGS_URL_FALLBACK.contains("Privacy_Pasteboard"));
        assert_ne!(SETTINGS_URL, SETTINGS_URL_FALLBACK);
    }
}
