/**
 * Authentication tests, driven by the frozen vectors in testdata/vectors.json.
 *
 * These are also the cross implementation check: the vectors were generated by the Rust
 * asli-crypto crate, so a Node side pass proves both implementations agree byte for byte on the
 * 121 byte signature input and on the room id derivation. A mismatch here means the wire format
 * diverged, which is a protocol break rather than a test to update.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { buildSigInput, roomIdForPublicKey, verifyAuth, SIG_INPUT_LEN } from '../src/auth.ts';
import type { NonceState } from '../src/auth.ts';
import type { AuthFields } from '../src/validate.ts';

type Vectors = {
  pub_key: string;
  room_id: string;
  room_id_bytes: string;
  auth: {
    nonce_s: string;
    nonce_c: string;
    client_time_ms: number;
    sig_input: string;
    signature: string;
  };
};

const vectors = JSON.parse(
  readFileSync(new URL('../../testdata/vectors.json', import.meta.url), 'utf8'),
) as Vectors;

const pubKey = Buffer.from(vectors.pub_key, 'hex');
const nonceS = Buffer.from(vectors.auth.nonce_s, 'hex');
const nonceC = Buffer.from(vectors.auth.nonce_c, 'hex');
const signature = Buffer.from(vectors.auth.signature, 'hex');
const roomIdBytes = Buffer.from(vectors.room_id_bytes, 'hex');

function fields(overrides: Partial<AuthFields> = {}): AuthFields {
  return {
    roomText: vectors.room_id,
    pubKey,
    nonceC,
    clientTimeMs: vectors.auth.client_time_ms,
    sig: signature,
    ...overrides,
  };
}

function issued(): NonceState {
  return { issued: Buffer.from(nonceS) };
}

test('the room id derivation matches the frozen vector', () => {
  assert.equal(roomIdForPublicKey(pubKey).toString('hex'), vectors.room_id_bytes);
});

test('the signature input matches the frozen vector byte for byte', () => {
  const input = buildSigInput({
    version: 1,
    roomIdBytes,
    pubKey,
    nonceS,
    nonceC,
    clientTimeMs: vectors.auth.client_time_ms,
  });
  assert.equal(input.length, SIG_INPUT_LEN);
  assert.equal(input.toString('hex'), vectors.auth.sig_input);
});

test('a valid signature from the reference implementation is accepted', () => {
  const result = verifyAuth(fields(), issued(), false);
  assert.equal(result.ok, true, result.ok ? '' : `rejected with ${result.code}`);
  if (!result.ok) return;
  assert.equal(result.roomId, vectors.room_id);
});

test('a tampered signature is rejected', () => {
  const bad = Buffer.from(signature);
  bad[0] = (bad[0] ?? 0) ^ 0x01;
  const result = verifyAuth(fields({ sig: bad }), issued(), false);
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.equal(result.code, 'BAD_SIGNATURE');
  assert.equal(result.close, 4002);
});

test('a signature over a different nonce is rejected', () => {
  const otherNonce: NonceState = { issued: Buffer.alloc(32, 0xcc) };
  const result = verifyAuth(fields(), otherNonce, false);
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.equal(result.code, 'BAD_SIGNATURE');
});

test('a room id that does not match the public key is rejected before any signature work', () => {
  // The first character is mutated rather than the last. 26 Crockford characters carry 130 bits,
  // so the final character's two trailing bits must be zero for a 16 byte value; changing it would
  // produce a non canonical encoding and be rejected as malformed before the binding is ever
  // checked, which is a different failure from the one under test.
  const wrongRoom = (vectors.room_id[0] === 'F' ? 'G' : 'F') + vectors.room_id.slice(1);
  const result = verifyAuth(fields({ roomText: wrongRoom }), issued(), false);
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.equal(result.code, 'ROOM_MISMATCH');
  assert.equal(result.close, 4003);
});

test('a malformed room id is rejected', () => {
  for (const bad of ['U'.repeat(26), 'short', '!'.repeat(26)]) {
    const result = verifyAuth(fields({ roomText: bad }), issued(), false);
    assert.equal(result.ok, false);
    if (result.ok) continue;
    assert.equal(result.code, 'MALFORMED_AUTH');
  }
});

test('the challenge nonce is single use, even after a failure', () => {
  const state = issued();

  // First attempt fails on the signature, and must still consume the nonce.
  const bad = Buffer.from(signature);
  bad[5] = (bad[5] ?? 0) ^ 0xff;
  const first = verifyAuth(fields({ sig: bad }), state, false);
  assert.equal(first.ok, false);

  // The correct signature now fails, because the nonce it was issued against is gone.
  const second = verifyAuth(fields(), state, false);
  assert.equal(second.ok, false);
  if (second.ok) return;
  assert.equal(second.code, 'STALE_NONCE');
});

test('a handshake that overran the timeout is rejected even when everything else is valid', () => {
  const result = verifyAuth(fields(), issued(), true);
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.equal(result.code, 'AUTH_TIMEOUT');
  assert.equal(result.close, 4001);
});

test('a public key that is not a valid encoding is rejected', () => {
  const result = verifyAuth(fields({ pubKey: Buffer.alloc(32, 0xff) }), issued(), false);
  assert.equal(result.ok, false);
  if (result.ok) return;
  // Either the key fails to import or the room binding fails first. Both are closed failures.
  assert.ok(['MALFORMED_AUTH', 'ROOM_MISMATCH'].includes(result.code));
});
